### PR TITLE
Edits to the manuscript

### PR DESCRIPTION
**Pull request by jeizenga**
@ekg 
I've added a few comments and edited a bit for style/accuracy. Generally speaking, I think the shift in direction you're going for works. I still have some issues with Figure 2 however, which I don't think is really publication-quality yet. Also, the role of XG is somewhat unclear in this manuscript, so we should make a decision on how to approach it. More detailed comments in the \todo notes.

### CODE REVIEW

**Comment by ekg** [comment]
@jeizenga I'm assuming that these are your comments. Is there more to do?

**Comment by ekg** [comment]
@jeizenga I'd like to get figure 1 to match the colors used in figure 2, not the other way around. Is the code to generate figure 1 in the repo?

**Comment by jeizenga** [comment]
It's public in this repository https://github.com/jeizenga/handle_eval
I think it's a bit out of date at this point though

**Comment by ekg** [comment]
@jeizenga would you please re-run and post the table that you're plotting?

I'd really like to harmonize the colors and it would also be good to bring it up to date.

After the edits I'm making (and extension to the experiments/discussion) this should be the major outstanding issue with the results.

**Comment by jeizenga** [comment]
@ekg Sure I can do that today

**Pull request merged**
